### ISSUE TITLE
move the archer trainer

### ISSUE THREAD

**Issue by seiyria** [IdleLands/Maps#26]
I think he should be moved to somewhere more "archer-y" and possibly adjust that particular area to be more difficult.

Here are my ideas:

* SE of minotaur entrance, change that area to be a giant forest maze
* above Maeles, in its own forest map. (in the source material, there is a way to get above the town) - this could possibly come with a very difficult-to-traverse maze and it could have teleports either to the beginning, or out to Maeles.

open to more ideas, but lets get him out there and make him a tough-to-find class.

**Comment by sedgwick** [comment]
I'm assuming the new minotaur forest is the one you meant, not olde minotaur forest. If so, then I think that's a better choice then making a new map above Maeles. I could rework this area as you suggested. 

http://puu.sh/qSWUz/1ed7977578.png

Another idea that came off the top of my head is a bit... brutal. Funhouse -2 has a shooting gallery. But, you have to successfully navigate 10 portals (without touching the wrong one putting you at the beginning of the funhouse).

http://puu.sh/qSX3q/5bfd551b1b.png

Last, the reference material mentioned that a mentalist trainer goes near the leviathan/giant tower area. I'm thinking block off the grass/trees section with rocks on E side, add stairs in giant's tower that lead up to this area. Maybe make it a little bigger to add a little building/collectible/some kind of archer decor. Make it a little more snowy too.

http://puu.sh/qSXs4/9db700356b.png

**Comment by seiyria** [comment]
Yes, I meant that area. Thanks for catching that.

I think I would like to put a class in the funhouse, but I don't think it will be the archer. Lets reserve the funhouse for a new class. I think if I ever make the [Magician](https://github.com/IdleLands/IdleLandsOld/issues/401), he would fit in better there.

Yes, that reference is a bit off - it was actually a hybrid class (fighter and mentalist). That said, I'm ok putting the archer down there if that's what you're getting at, but I still would want it to be "tough" getting to him (ie, like the forest maze). That said, instead of making a new map, you could just expand the cloud giant area map, I think, and make this a new area that goes way off to the right.

**Comment by sedgwick** [comment]
Current plan is to modify the giant's tower map to include a new region for the archer trainer. Region can be called Archer's Forest. Though, I believe the Giant's Tower map could be renamed to something like Leviathan Mountain with Giant's Tower/Archer's Forest being regions, similar to how Vocalnus is the map with other areas being regions.

So, to make sure I really understand the plan: 
* Add stairs around here http://puu.sh/qSYML/e130076f0f.png
* Giant's Tower map extended further on right edge, and probably south edge as well.
* Add a pitfall covered rock land bridge, south of giant's tower region heading east which would put the area over the sea in first screenshot.
* Add some rocks on Norkos to represent the mountain support of new area.

**Comment by seiyria** [comment]
Yes, this sounds correct.

**Comment by sedgwick** [comment]
Updated Giant's tower a bit too, and added a room for those with the crystal of air. He used it as a key for his bed/treasure room. Added a region for Giant's Tower.

Moving the Giant's Tower map to the world folder, and renaming the map Leviathan Mountain since there are multiple unconnected regions on the map.

Added Archer's Forest region accessible off of Norkos (moved the tree area a bit, here is also the picture of the bridge from Norkos http://puu.sh/qTPYZ/d34c468612.png)

https://puu.sh/qTPRn/a23ff49674.png I picture it like a mountainous redwood forest. A twisting path leads up the mountain to the bridge over the sea. A few pitfalls means you've gotta make your chance at the archer count. Think it's too much?

**Comment by sedgwick** [comment]
Another option is to do something with that valley on norkos. it's part of the leviathan mountain region and not wilderness. I could decorate it like the archer's forest instead of grassy forest.

**Comment by seiyria** [comment]
I like what you have so far (and strangely the tree on dirt look doesn't seem to be that common, so it looks nice here). I think it should go out farther to the right though - lets make it a tough one. People will still find a way, but we can give them a boat of a time trying to do it anyway!

**Comment by sedgwick** [comment]
I do realize i blocked one of the pitfalls, fixing that.

**Comment by sedgwick** [comment]
http://puu.sh/qTQZ2/95e08047aa.png
Changed the Norkos region, added a Feathered Cap collectible for memoir: archer.
Extending the landbridge also makes it a little harder to get to the area with the support rocks now, so that adds an extra layer to navigating the region.

http://puu.sh/qTRbb/9de48fedbf.png
http://puu.sh/qTRad/570ef70a1c.png

**Comment by seiyria** [comment]
Perfect. I like it.

**Comment by sedgwick** [comment]
Complete with #27.
